// <auto-generated />
using System;
using FIAP.Hackathon.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FIAP.Hackathon.Infrastructure.Migrations
{
    [DbContext(typeof(HackathonDBContext))]
    [Migration("20250429023957_InitialDataBase")]
    partial class InitialDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FIAP.Hackathon.Domain.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("AgendamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MedicoAgendaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer");

                    b.HasKey("AgendamentoId");

                    b.HasIndex("MedicoAgendaId");

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("FIAP.Hackathon.Domain.Entities.MedicoAgenda", b =>
                {
                    b.Property<Guid>("MedicoAgendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EspecialidadeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer");

                    b.HasKey("MedicoAgendaId");

                    b.ToTable("MedicoAgenda");
                });

            modelBuilder.Entity("FIAP.Hackathon.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("FIAP.Hackathon.Domain.Entities.MedicoAgenda", "MedicoAgenda")
                        .WithMany("Agendamentos")
                        .HasForeignKey("MedicoAgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicoAgenda");
                });

            modelBuilder.Entity("FIAP.Hackathon.Domain.Entities.MedicoAgenda", b =>
                {
                    b.Navigation("Agendamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
